### ISSUE TITLE
What is proper config entry with latest update?

### ISSUE THREAD

**Issue by Protoncek** [arturpragacz/hass-cc-default-config-exclude#1]
Hi!

Sorry to bother, but i don't quite understand latest update/change... before i've had this in my config file:

```
default_config:
default_config_exclude:
  early_loader_hook: true
  exclude:
    - cloud
    - backup
    - conversation
    - energy
    - map
```
but with latest version - if i understand correctly - now above should change to:
```
default_config:
default_config_exclude: 
  - cloud
  - backup
  - conversation
  - energy
  - map
```

Also - is "early loader..." entry still needed? If so, where to put it? 

Otherwise, maaaany thanks for this addon, it's extremly usefull!!!
